
CREATE TABLE Fecha 
(
	fechaID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	anno smallint NOT NULL,
	mes smallint NOT NULL,
	dia smallint NOT NULL,
	parteDia time NOT NULL,
	CONSTRAINT fecha_pkey PRIMARY KEY(fechaID)
);

CREATE TABLE Lugar 
(
	lugarID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	pais varchar(50) NOT NULL,
	ciudad varchar(50) NOT NULL,
	tienda varchar(50) NOT NULL,
	CONSTRAINT lugar_pkey PRIMARY KEY(lugarID)
);

CREATE TABLE Pelicula 
(
	peliculaID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	filme varchar(50) NOT NULL,
	categoria varchar(50) NOT NULL, 
	CONSTRAINT pelicula_pkey PRIMARY KEY(peliculaID)
);

CREATE TABLE Lenguaje 
(
	lenguajeID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	lenguaje varchar(50), 
	CONSTRAINT lenguaje_pkey PRIMARY KEY(lenguajeID)
);

CREATE TABLE Duracion 
(
	duracionID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
	duracion smallint, 
	CONSTRAINT duracion_pkey PRIMARY KEY(duracionID)
);

CREATE TABLE Ventas
(
	ventasID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	fechaID integer NOT NULL, 
	peliculaID integer NOT NULL, 
	lenguajeID integer NOT NULL, 
	lugarID integer NOT NULL,
	duracionID integer NOT NULL, 
	unidadesVendidas integer NOT NULL, 
	montoVendido numeric(19,4) NOT NULL,
	CONSTRAINT ventas_fecha_fkey FOREIGN KEY(fechaID)
	REFERENCES public.Fecha(fechaID),
	CONSTRAINT ventas_pelicula_fkey FOREIGN KEY(peliculaID)
	REFERENCES public.Pelicula(peliculaID),
	CONSTRAINT ventas_lenguaje_fkey FOREIGN KEY(lenguajeID)
	REFERENCES public.Lenguaje(lenguajeID),
	CONSTRAINT ventas_lugar_fkey FOREIGN KEY(lugarID)
	REFERENCES public.Lugar(lugarID),
	CONSTRAINT ventas_duracion_fkey FOREIGN KEY(duracionID)
	REFERENCES public.Duracion(duracionID)
);







